<a href="https://colab.research.google.com/github/boskidisanalysis/Electricity-Consumption/blob/main/Energy_Consumption.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 
import plotly.express as px

In [ ]:
df = pd.read_csv('/content/global-energy-substitution.xls')

In [ ]:
df.head()

  Entity  ... Gas (TWh; substituted energy)
0  World  ...                             0
1  World  ...                             0
2  World  ...                             0
3  World  ...                             0
4  World  ...                             0

[5 rows x 13 columns]

In [ ]:
df['Total'] = df[3:].sum(axis=0)

In [ ]:
df.head()

  Entity      Code  ...  Gas (TWh; substituted energy)  Total
0  World  OWID_WRL  ...                              0    NaN
1  World  OWID_WRL  ...                              0    NaN
2  World  OWID_WRL  ...                              0    NaN
3  World  OWID_WRL  ...                              0    NaN
4  World  OWID_WRL  ...                              0    NaN

[5 rows x 14 columns]

In [ ]:
df.Total = df.iloc[:,3:].sum(axis=1)

In [ ]:
df.head()

  Entity      Code  ...  Gas (TWh; substituted energy)   Total
0  World  OWID_WRL  ...                              0  5653.0
1  World  OWID_WRL  ...                              0  5961.0
2  World  OWID_WRL  ...                              0  6264.0
3  World  OWID_WRL  ...                              0  6653.0
4  World  OWID_WRL  ...                              0  7300.0

[5 rows x 14 columns]

In [ ]:
melted = df.iloc[:,2:].melt(id_vars='Year')
melted.head()

   Year                        variable  value
0  1800  Wind (TWh; substituted energy)    0.0
1  1810  Wind (TWh; substituted energy)    0.0
2  1820  Wind (TWh; substituted energy)    0.0
3  1830  Wind (TWh; substituted energy)    0.0
4  1840  Wind (TWh; substituted energy)    0.0

In [ ]:
fig = px.area(data_frame=melted, x='Year', y='value', color='variable', labels={
    'value': 'Electricity Consumption (TWh)'
}, 
    title ='Global Electricity Consumption')

fig.for_each_trace(lambda t: t.update(name=t.name.split("=")[1]))
fig.for_each_trace(lambda t: t.update(name=t.name.split("(")[0]))
# fig.layout.yaxis.update(matches=None)

# fig.update_layout(legend=dict(
#     orientation="h",
#     yanchor="bottom",
#     y=1.02,
#     xanchor="right",
#     x=1
# ))

# fig.for_each_annotation(lambda a: a.update(text=a.text.split("=")[-1]))
# fig.for_each_annotation(lambda a: a.update(textangle=0))
# #fig.update_layout(showlegend=False)
fig.show()